### PR TITLE
Docs add article

### PR DESCRIPTION
**Pull request by dmihaylo**
@tsvetomir & @KirilNN 

Guys, please review - I might be missing something. 

Related to: 
- Issue #2093 
- [Pull Request](https://github.com/telerik/kendo-ui-core/pull/2314) 

Resources used:     
- [https://github.com/telerik/kendo-ui-sharepoint-2013-demo](https://github.com/telerik/kendo-ui-sharepoint-2013-demo) 
- [http://developer.telerik.com/featured/building-sharepoint-add-ins-with-kendo-ui/](http://developer.telerik.com/featured/building-sharepoint-add-ins-with-kendo-ui/)

### CODE REVIEW

**Comment by tsvetomir** [comment]
Looks good!

**Comment by KirilNN** [comment]
Do you guys think that we should add a link in the Kendo UI documentation site as well?

**Comment by dmihaylo** [comment]
It looks like a very good idea to add a new line **Third-Party Integration** or similar to [http://docs.telerik.com/](http://docs.telerik.com/) under the **Framework and Utilities** section. Shall let you know when finished so we can close the issue.

**Comment by dmihaylo** [comment]
Updates are now deployed to [http://docs.telerik.com/](http://docs.telerik.com/). 

This PR is related to [https://github.com/telerik/kendo-ui-core/pull/2314#issuecomment-253792966](https://github.com/telerik/kendo-ui-core/pull/2314#issuecomment-253792966) and [https://github.com/telerik/kendo-ui-core/issues/2093](https://github.com/telerik/kendo-ui-core/issues/2093).

**Pull request merged**
